---
kind: pipeline
type: docker
name: default
steps:
  - name: ansible-check
    image: quay.io/ansible/toolset:0.5
    commands:
      - "[ -f './collections/requirements.yml' ] && ansible-galaxy install -r ./collections/requirements.yml || echo 'No requirements file active.'"
      - "[ -f './roles/requirements.yml' ] && ansible-galaxy install -r ./roles/requirements.yml || echo 'No requirements file active.'"
      - "find ./playbooks -maxdepth 1 -name '*.yml' | xargs ansible-playbook --syntax-check --list-tasks"
      - "find ./playbooks -maxdepth 1 -name '*.yml' | xargs ansible-lint"
