---
- name: Install package
  become: true
  ignore_errors: true
  when: item.profile is defined
  ansible.builtin.dnf:
    name: "@{{ item.name }}:{{ item.stream }}/{{ item.profile }}"
    state: present

- name: Profile less streams
  when: item.profile is undefined
  block:
    - name: Enable module stream
      become: true
      ansible.builtin.copy:
        content: |
          [{{ item.name }}]
          name={{ item.name }}
          stream={{ item.stream }}
          profiles=
          state=enabled
        dest: "/etc/dnf/modules.d/{{ item.name }}.module"
        owner: root
        group: root
        mode: o=rw,g=r,o=r

    - name: Install packages
      become: true
      ignore_errors: true
      ansible.builtin.dnf:
        name: "{{ item.packages }}"
        state: present

- name: Revert to snapshot
  community.vmware.vmware_guest_snapshot:
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ vcenter_systemname }}"
    folder: "{{ vcenter_folder }}"
    snapshot_name: ansible_snapshot
    state: revert
  delegate_to: localhost

- name: Make sure the system is powered on
  community.vmware.vmware_guest:
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ vcenter_systemname }}"
    folder: "{{ vcenter_folder }}"
    state: powered-on
    wait_for_ip_address: true
  delegate_to: localhost
