---
- name: vCenter setup tasks
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vcenter.yml
  pre_tasks:
    - name: Check if all needed variables are available
      ansible.builtin.assert:
        that:
          - vcenter_systemname | mandatory
  tasks:
    - name: Setup
      ansible.builtin.include_tasks: setup.yml

- name: Module check tasks
  hosts: temporary
  vars_files:
    - vars/vcenter.yml
    - vars/modules.yml
  pre_tasks:
    - name: Check if all needed variables are available
      ansible.builtin.assert:
        that:
          - vcenter_systemname | mandatory
  tasks:
    - name: Module checks
      with_items: "{{ module_streams }}"
      ansible.builtin.include_tasks: module_checks.yml
